from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HelpDialog(object):
    def setupUi(self, HelpDialog):
        HelpDialog.setObjectName("HelpDialog")
        HelpDialog.resize(742, 490)
        HelpDialog.setMinimumSize(QtCore.QSize(742, 300))
        HelpDialog.setMaximumSize(QtCore.QSize(742, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Media\icon\icon1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HelpDialog.setWindowIcon(icon)
        self.horizontalLayoutWidget = QtWidgets.QWidget(HelpDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 220, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.judulScreen = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.judulScreen.setContentsMargins(0, 0, 0, 0)
        self.judulScreen.setObjectName("judulScreen")

        self.picBantuan = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picBantuan.sizePolicy().hasHeightForWidth())
        self.picBantuan.setStyleSheet("")
        self.picBantuan.setText("")
        self.picBantuan.setPixmap(QtGui.QPixmap("Media\icon\IconBantuan.png"))
        self.picBantuan.resize(64,64)
        self.picBantuan.setScaledContents(False)
        self.picBantuan.setObjectName("picBantuan")
        self.judulScreen.addWidget(self.picBantuan)

        self.textBantuan = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textBantuan.setFont(font)
        self.textBantuan.setObjectName("textBantuan")
        self.judulScreen.addWidget(self.textBantuan)

        self.Bantuan4 = QtWidgets.QLabel(HelpDialog)
        self.Bantuan4.setGeometry(QtCore.QRect(30, 190, 730, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bantuan4.sizePolicy().hasHeightForWidth())
        self.Bantuan4.setSizePolicy(sizePolicy)
        self.Bantuan4.setObjectName("Bantuan4")

        self.Bantuan2 = QtWidgets.QLabel(HelpDialog)
        self.Bantuan2.setGeometry(QtCore.QRect(30, 140, 730, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bantuan2.sizePolicy().hasHeightForWidth())
        self.Bantuan2.setSizePolicy(sizePolicy)
        self.Bantuan2.setObjectName("Bantuan2")

        self.Bantuan5 = QtWidgets.QLabel(HelpDialog)
        self.Bantuan5.setGeometry(QtCore.QRect(30, 215, 730, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bantuan5.sizePolicy().hasHeightForWidth())
        self.Bantuan5.setSizePolicy(sizePolicy)
        self.Bantuan5.setObjectName("Bantuan5")

        self.Bantuan3 = QtWidgets.QLabel(HelpDialog)
        self.Bantuan3.setGeometry(QtCore.QRect(30, 165, 730, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bantuan3.sizePolicy().hasHeightForWidth())
        self.Bantuan3.setSizePolicy(sizePolicy)
        self.Bantuan3.setObjectName("Bantuan3")

        self.Bantuan1 = QtWidgets.QLabel(HelpDialog)
        self.Bantuan1.setGeometry(QtCore.QRect(30, 115, 730, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bantuan1.sizePolicy().hasHeightForWidth())
        self.Bantuan1.setSizePolicy(sizePolicy)
        self.Bantuan1.setObjectName("Bantuan1")

        font2 = QtGui.QFont()
        font2.setFamily("Tahoma")
        font2.setPointSize(9)
        self.Bantuan1.setFont(font2)
        self.Bantuan2.setFont(font2)
        self.Bantuan3.setFont(font2)
        self.Bantuan4.setFont(font2)
        self.Bantuan5.setFont(font2)

        self.retranslateUi(HelpDialog)
        QtCore.QMetaObject.connectSlotsByName(HelpDialog)

    def retranslateUi(self, HelpDialog):
        _translate = QtCore.QCoreApplication.translate
        HelpDialog.setWindowTitle(_translate("HelpDialog", "Bantuan"))
        self.textBantuan.setText(_translate("HelpDialog", "Bantuan"))
        self.Bantuan4.setText(_translate("HelpDialog", "4. Untuk melakukan pemrosesan gambar lainnya (grayscale, erode,dll), klik kanan saat citra dimuat"))
        self.Bantuan2.setText(_translate("HelpDialog", "2. Untuk menggunakan kamera, pilih menu: URL perangkat. Sedangkan file video, di menu: Pilih File"))
        self.Bantuan5.setText(_translate("HelpDialog", "5. Panduan lengkap mengenai aplikasi ini bisa dilihat pada buku panduan yang dilampirkan"))
        self.Bantuan3.setText(_translate("HelpDialog", "3. Ketentuan mengenai URL perangkat bisa dilihat pada buku panduan"))
        self.Bantuan1.setText(_translate("HelpDialog", "1. Pilih tombol :Hubungkan Kamera/Video - Untuk membuka menu pengaturan kamera/video"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HelpDialog = QtWidgets.QDialog(None, QtCore.Qt.WindowSystemMenuHint | QtCore.Qt.WindowTitleHint)
    ui = Ui_HelpDialog()
    ui.setupUi(HelpDialog)
    HelpDialog.show()
    sys.exit(app.exec_())
