# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TujuanScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TujuanDialog(object):
    def setupUi(self, TujuanDialog):
        TujuanDialog.setObjectName("TujuanDialog")
        TujuanDialog.resize(742, 490)
        TujuanDialog.setMinimumSize(QtCore.QSize(742, 490))
        TujuanDialog.setMaximumSize(QtCore.QSize(742, 490))
        self.horizontalLayoutWidget = QtWidgets.QWidget(TujuanDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 291, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.judulScreen = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.judulScreen.setContentsMargins(0, 0, 0, 0)
        self.judulScreen.setObjectName("judulScreen")
        self.picTujuan = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picTujuan.sizePolicy().hasHeightForWidth())
        self.picTujuan.setSizePolicy(sizePolicy)
        self.picTujuan.setStyleSheet("")
        self.picTujuan.setText("")
        self.picTujuan.setPixmap(QtGui.QPixmap("../../../../Gambar/285716ce4271f4bd9cf8c6a7ae30879f.gif"))
        self.picTujuan.setScaledContents(True)
        self.picTujuan.setObjectName("picTujuan")
        self.judulScreen.addWidget(self.picTujuan)
        self.textTujuan = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textTujuan.setFont(font)
        self.textTujuan.setObjectName("textTujuan")
        self.judulScreen.addWidget(self.textTujuan)
        self.Tujuan4 = QtWidgets.QLabel(TujuanDialog)
        self.Tujuan4.setGeometry(QtCore.QRect(30, 190, 681, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tujuan4.sizePolicy().hasHeightForWidth())
        self.Tujuan4.setSizePolicy(sizePolicy)
        self.Tujuan4.setObjectName("Tujuan4")
        self.Tujuan2 = QtWidgets.QLabel(TujuanDialog)
        self.Tujuan2.setGeometry(QtCore.QRect(30, 130, 681, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tujuan2.sizePolicy().hasHeightForWidth())
        self.Tujuan2.setSizePolicy(sizePolicy)
        self.Tujuan2.setObjectName("Tujuan2")
        self.Tujuan5 = QtWidgets.QLabel(TujuanDialog)
        self.Tujuan5.setGeometry(QtCore.QRect(30, 220, 681, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tujuan5.sizePolicy().hasHeightForWidth())
        self.Tujuan5.setSizePolicy(sizePolicy)
        self.Tujuan5.setObjectName("Tujuan5")
        self.Tujuan3 = QtWidgets.QLabel(TujuanDialog)
        self.Tujuan3.setGeometry(QtCore.QRect(30, 160, 681, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tujuan3.sizePolicy().hasHeightForWidth())
        self.Tujuan3.setSizePolicy(sizePolicy)
        self.Tujuan3.setObjectName("Tujuan3")
        self.Tujuan1 = QtWidgets.QLabel(TujuanDialog)
        self.Tujuan1.setGeometry(QtCore.QRect(30, 110, 434, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tujuan1.sizePolicy().hasHeightForWidth())
        self.Tujuan1.setSizePolicy(sizePolicy)
        self.Tujuan1.setObjectName("Tujuan1")
        self.Tujuan6 = QtWidgets.QLabel(TujuanDialog)
        self.Tujuan6.setGeometry(QtCore.QRect(36, 270, 671, 41))
        self.Tujuan6.setObjectName("Tujuan6")
        self.closeTujuanBtn = QtWidgets.QPushButton(TujuanDialog)
        self.closeTujuanBtn.setGeometry(QtCore.QRect(350, 440, 80, 21))
        self.closeTujuanBtn.setObjectName("closeTujuanBtn")

        self.retranslateUi(TujuanDialog)
        QtCore.QMetaObject.connectSlotsByName(TujuanDialog)

    def retranslateUi(self, TujuanDialog):
        _translate = QtCore.QCoreApplication.translate
        TujuanDialog.setWindowTitle(_translate("TujuanDialog", "Connect to Camera"))
        self.textTujuan.setText(_translate("TujuanDialog", "Tujuan Pembelajaran"))
        self.Tujuan4.setText(_translate("TujuanDialog", "4. Membantu peserta didik memahami serta mengaplikasikan bidang Deteksi dan Pelacakan Objek, terkhusus pada komponen Resistor, Kapasitor, D"))
        self.Tujuan2.setText(_translate("TujuanDialog", "2. Menarik minat peserta didik untuk mempelajari serta mendalami materi Penginderaan Visual Robot"))
        self.Tujuan5.setText(_translate("TujuanDialog", "5. Membantu peserta didik memahami pendeteksian objek menggunakan metode Deep Learning terkhusus metode YOLOv3"))
        self.Tujuan3.setText(_translate("TujuanDialog", "3. Membantu peserta didik memahami serta mengaplikasikan macam-macam pengolahan citra"))
        self.Tujuan1.setText(_translate("TujuanDialog", "1. Menjadi media belajar untuk membantu proses pembelajaran Penginderaan Visual Robot"))
        self.Tujuan6.setText(_translate("TujuanDialog", "Tulis disinii oke"))
        self.closeTujuanBtn.setText(_translate("TujuanDialog", "Tutup"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TujuanDialog = QtWidgets.QDialog()
    ui = Ui_TujuanDialog()
    ui.setupUi(TujuanDialog)
    TujuanDialog.show()
    sys.exit(app.exec_())
