
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CameraConnectDialog(object):
    def setupUi(self, CameraConnectDialog):
        CameraConnectDialog.setObjectName("CameraConnectDialog")
        CameraConnectDialog.resize(742, 200)
        CameraConnectDialog.setMinimumSize(QtCore.QSize(742, 200))
        CameraConnectDialog.setMaximumSize(QtCore.QSize(742, 200))
        self.layoutWidget = QtWidgets.QWidget(CameraConnectDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 721, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_1 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.verticalLayout_3.addWidget(self.label_1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.deviceUrlRadioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.deviceUrlRadioButton.setObjectName("deviceUrlRadioButton")
        self.horizontalLayout_12.addWidget(self.deviceUrlRadioButton)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        self.deviceUrlEdit = QtWidgets.QComboBox(self.layoutWidget)
        self.deviceUrlEdit.setObjectName("deviceUrlEdit")
        self.horizontalLayout_65.addWidget(self.deviceUrlEdit)
        self.horizontalLayout_65.setStretch(0, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_65)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.filenameRadioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.filenameRadioButton.setObjectName("filenameRadioButton")
        self.horizontalLayout_10.addWidget(self.filenameRadioButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.importFilePushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.importFilePushButton.setObjectName("importFilePushButton")
        self.horizontalLayout_10.addWidget(self.importFilePushButton)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_10)
        self.filenameEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.filenameEdit.setObjectName("filenameEdit")
        self.horizontalLayout_9.addWidget(self.filenameEdit)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_13.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.resWEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.resWEdit.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.resWEdit.setFont(font)
        self.resWEdit.setObjectName("resWEdit")
        self.horizontalLayout_14.addWidget(self.resWEdit)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_14.addWidget(self.label_13)
        self.resHEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.resHEdit.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.resHEdit.setFont(font)
        self.resHEdit.setObjectName("resHEdit")
        self.horizontalLayout_14.addWidget(self.resHEdit)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.tabLabelEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabLabelEdit.setFont(font)
        self.tabLabelEdit.setObjectName("tabLabelEdit")
        self.horizontalLayout_5.addWidget(self.tabLabelEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.resetToDefaultsPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.resetToDefaultsPushButton.setObjectName("resetToDefaultsPushButton")
        self.horizontalLayout_4.addWidget(self.resetToDefaultsPushButton)
        self.okCancelBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.okCancelBox.setOrientation(QtCore.Qt.Horizontal)
        self.okCancelBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.okCancelBox.setObjectName("okCancelBox")
        self.horizontalLayout_4.addWidget(self.okCancelBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)

        self.retranslateUi(CameraConnectDialog)
        self.okCancelBox.accepted.connect(CameraConnectDialog.accept)
        self.okCancelBox.rejected.connect(CameraConnectDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CameraConnectDialog)
        CameraConnectDialog.setTabOrder(self.deviceUrlRadioButton, self.deviceUrlEdit)
        CameraConnectDialog.setTabOrder(self.deviceUrlEdit, self.filenameEdit)
        CameraConnectDialog.setTabOrder(self.filenameEdit, self.resWEdit)
        CameraConnectDialog.setTabOrder(self.resWEdit, self.resHEdit)
        CameraConnectDialog.setTabOrder(self.resHEdit, self.tabLabelEdit)
        CameraConnectDialog.setTabOrder(self.tabLabelEdit, self.resetToDefaultsPushButton)

    def retranslateUi(self, CameraConnectDialog):
        _translate = QtCore.QCoreApplication.translate
        CameraConnectDialog.setWindowTitle(_translate("CameraConnectDialog", "Hubungkan ke kamera"))
        self.label_1.setText(_translate("CameraConnectDialog", "Kamera:"))
        self.deviceUrlRadioButton.setText(_translate("CameraConnectDialog", "URL perangkat:"))
        self.label_10.setText(_translate("CameraConnectDialog", "[0, 1, 2, ...]"))
        self.filenameRadioButton.setText(_translate("CameraConnectDialog", "Direktrori file:"))
        self.importFilePushButton.setText(_translate("CameraConnectDialog", "Import"))
        self.label_11.setText(_translate("CameraConnectDialog", "Resolusi (W x H):"))
        self.label_12.setText(_translate("CameraConnectDialog", "[optional]"))
        self.label_13.setText(_translate("CameraConnectDialog", "x"))
        self.label_8.setText(_translate("CameraConnectDialog", "Tab Label:"))
        self.resetToDefaultsPushButton.setText(_translate("CameraConnectDialog", "Reset ke Defaults"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CameraConnectDialog = QtWidgets.QDialog()
    ui = Ui_CameraConnectDialog()
    ui.setupUi(CameraConnectDialog)
    CameraConnectDialog.show()
    sys.exit(app.exec_())
