from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from ui_TujuanScreen import Ui_TujuanDialog as Form
from AboutScreen import Ui_AboutDialog as Form2
from HelpScreen import Ui_HelpDialog as Form3

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.setWindowIcon(QtGui.QIcon('Media\icon\icon1.png'))
        self.showMaximized()
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tujuanButton = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tujuanButton.sizePolicy().hasHeightForWidth())
        self.tujuanButton.setSizePolicy(sizePolicy)
        self.tujuanButton.setObjectName("tujuanButton")
        self.tujuanButton.clicked.connect(self.open_Tujuandialog)
        self.horizontalLayout_2.addWidget(self.tujuanButton)

        self.bantuanButton = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bantuanButton.sizePolicy().hasHeightForWidth())
        self.bantuanButton.setSizePolicy(sizePolicy)
        self.bantuanButton.setObjectName("bantuanButton")
        self.bantuanButton.clicked.connect(self.open_Helpdialog)
        self.horizontalLayout_2.addWidget(self.bantuanButton)

        self.tentangButton = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bantuanButton.sizePolicy().hasHeightForWidth())
        self.tentangButton.setSizePolicy(sizePolicy)
        self.tentangButton.setObjectName("tentangButton")
        self.tentangButton.clicked.connect(self.open_Aboutdialog)
        self.horizontalLayout_2.addWidget(self.tentangButton)

        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_2.addItem(spacerItem)

        self.label_gambar = QtWidgets.QLabel(self.centralWidget)
        self.label_gambar.setStyleSheet("")
        self.label_gambar.setText("")
        self.label_gambar.setPixmap(QtGui.QPixmap("Media\Images\LogoApp.png"))
        self.label_gambar.setObjectName("label_gambar")
        self.horizontalLayout_2.addWidget(self.label_gambar)

        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_2.addItem(spacerItem)

        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("QTabBar::tab{height:17}")
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 668, 20))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")

        self.actionScaleToFitFrame = QtWidgets.QAction(MainWindow)
        self.actionScaleToFitFrame.setCheckable(True)
        self.actionScaleToFitFrame.setObjectName("actionScaleToFitFrame")
        self.actionFullScreen = QtWidgets.QAction(MainWindow)
        self.actionFullScreen.setCheckable(True)
        self.actionFullScreen.setObjectName("actionFullScreen")
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)

        self.menuView.addAction(self.actionFullScreen)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YOLOv3: Deteksi Komponen Elektronika"))
        self.tujuanButton.setText(_translate("MainWindow", "Tujuan"))
        self.bantuanButton.setText(_translate("MainWindow", "Bantuan"))
        self.tentangButton.setText(_translate("MainWindow", "Tentang"))
        self.label.setText(_translate("MainWindow", "Deteksi Objek Komponen Elektronika\ndengan YOLO v3"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Tentang"))
        self.menuView.setTitle(_translate("MainWindow", "View(&V)"))
        self.actionAbout.setText(_translate("MainWindow", "Tentang aplikasi"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

        self.actionScaleToFitFrame.setText(_translate("MainWindow", "Paskan ke layar"))
        self.actionFullScreen.setText(_translate("MainWindow", "Full Screen(&F)"))

    def open_Tujuandialog(self):
        TujuanDialog = QtWidgets.QDialog()
        TujuanDialog.ui = Form()
        TujuanDialog.ui.setupUi(TujuanDialog)
        TujuanDialog.exec_()
        TujuanDialog.show()

    def open_Aboutdialog(self):
        AboutDialog = QtWidgets.QDialog()
        AboutDialog.ui = Form2()
        AboutDialog.ui.setupUi(AboutDialog)
        AboutDialog.exec_()
        AboutDialog.show()

    def open_Helpdialog(self):
        HelpDialog = QtWidgets.QDialog()
        HelpDialog.ui = Form3()
        HelpDialog.ui.setupUi(HelpDialog)
        HelpDialog.exec_()
        HelpDialog.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
