from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TujuanDialog(object):
    def setupUi(self, TujuanDialog):
        TujuanDialog.setObjectName("TujuanDialog")
        TujuanDialog.resize(742, 490)
        TujuanDialog.setMinimumSize(QtCore.QSize(742, 300))
        TujuanDialog.setMaximumSize(QtCore.QSize(742, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Media\icon\icon1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TujuanDialog.setWindowIcon(icon)
        self.horizontalLayoutWidget = QtWidgets.QWidget(TujuanDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 300, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.judulScreen = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.judulScreen.setContentsMargins(0, 0, 0, 0)
        self.judulScreen.setObjectName("judulScreen")
        self.picTujuan = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picTujuan.sizePolicy().hasHeightForWidth())

        self.picTujuan.setStyleSheet("")
        self.picTujuan.setText("")
        self.picTujuan.setPixmap(QtGui.QPixmap("Media\icon\IconTujuan.png"))
        self.picTujuan.resize(64,64)
        self.picTujuan.setScaledContents(False)
        self.picTujuan.setObjectName("picTujuan")
        self.judulScreen.addWidget(self.picTujuan)

        self.textTujuan = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textTujuan.setFont(font)
        self.textTujuan.setObjectName("textTujuan")
        self.judulScreen.addWidget(self.textTujuan)

        self.Tujuan4 = QtWidgets.QLabel(TujuanDialog)
        self.Tujuan4.setGeometry(QtCore.QRect(30, 180, 700, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tujuan4.sizePolicy().hasHeightForWidth())
        self.Tujuan4.setSizePolicy(sizePolicy)
        self.Tujuan4.setObjectName("Tujuan4")

        self.Tujuan2 = QtWidgets.QLabel(TujuanDialog)
        self.Tujuan2.setGeometry(QtCore.QRect(30, 140, 700, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tujuan2.sizePolicy().hasHeightForWidth())
        self.Tujuan2.setSizePolicy(sizePolicy)
        self.Tujuan2.setObjectName("Tujuan2")

        self.Tujuan5 = QtWidgets.QLabel(TujuanDialog)
        self.Tujuan5.setGeometry(QtCore.QRect(30, 200, 700, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tujuan5.sizePolicy().hasHeightForWidth())
        self.Tujuan5.setSizePolicy(sizePolicy)
        self.Tujuan5.setObjectName("Tujuan5")

        self.Tujuan3 = QtWidgets.QLabel(TujuanDialog)
        self.Tujuan3.setGeometry(QtCore.QRect(30, 160, 700, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tujuan3.sizePolicy().hasHeightForWidth())
        self.Tujuan3.setSizePolicy(sizePolicy)
        self.Tujuan3.setObjectName("Tujuan3")

        self.Tujuan1 = QtWidgets.QLabel(TujuanDialog)
        self.Tujuan1.setGeometry(QtCore.QRect(30, 120, 700, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tujuan1.sizePolicy().hasHeightForWidth())
        self.Tujuan1.setSizePolicy(sizePolicy)
        self.Tujuan1.setObjectName("Tujuan1")

        font2 = QtGui.QFont()
        font2.setFamily("Tahoma")
        font2.setPointSize(9)
        self.Tujuan1.setFont(font2)
        self.Tujuan2.setFont(font2)
        self.Tujuan3.setFont(font2)
        self.Tujuan4.setFont(font2)
        self.Tujuan5.setFont(font2)

        self.retranslateUi(TujuanDialog)
        QtCore.QMetaObject.connectSlotsByName(TujuanDialog)

    def retranslateUi(self, TujuanDialog):
        _translate = QtCore.QCoreApplication.translate
        TujuanDialog.setWindowTitle(_translate("TujuanDialog", "Tujuan Pembelajaran"))
        self.textTujuan.setText(_translate("TujuanDialog", "Tujuan Pembelajaran"))
        self.Tujuan4.setText(_translate("TujuanDialog", "4. Membantu peserta didik memahami serta mengaplikasikan bidang deteksi objek pada komponen elektronika"))
        self.Tujuan2.setText(_translate("TujuanDialog", "2. Menarik minat peserta didik untuk mempelajari serta mendalami materi Penginderaan Visual Robot"))
        self.Tujuan5.setText(_translate("TujuanDialog", "5. Membantu peserta didik memahami pendeteksian objek menggunakan metode Deep Learning terkhusus metode YOLOv3"))
        self.Tujuan3.setText(_translate("TujuanDialog", "3. Membantu peserta didik memahami serta mengaplikasikan macam-macam pengolahan citra"))
        self.Tujuan1.setText(_translate("TujuanDialog", "1. Menjadi media belajar untuk membantu proses pembelajaran Penginderaan Visual Robot"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TujuanDialog = QtWidgets.QDialog(None, QtCore.Qt.WindowSystemMenuHint | QtCore.Qt.WindowTitleHint)
    ui = Ui_TujuanDialog()
    ui.setupUi(TujuanDialog)
    TujuanDialog.show()
    sys.exit(app.exec_())
